defaults:
  - _self_

method_name: ???  # choose among {baseline, rejection, best_of_n}
num_constraints: ??? # choose among {1, 2, 3}
experiment_name: ${now:%m-%d_%H-%M-%S}_${model.dataset}_${num_constraints}_${method_name}
ckpt_path: ComposableDiff/models/${model.dataset}.pt
data_path: ComposableDiff/dataset/test_${model.dataset}_5000_${num_constraints}.npz
output_dir: runs/${now:%m-%d_%H-%M-%S}

# for inference
batch_size: 32
cfg_weight: 7.5
# for evaluation
max_samples_for_generation: 100
mini_batch: 10

# for rejection sampling
rejection:
  eval_batch_size: 10
  mini_batch: ${mini_batch}
  reject_using_interval: false

# for best_of_n sampling
best_of_n:
  n: 10
  mini_batch: ${mini_batch}

# for ELBO estimation
elbo:
  use_cfg: false  # better to use no cfg for ELBO
  n_samples: 100
  same_noise: false  # if true, sample the same epsilon for all (t, epsilon) pairs
  sample_timesteps: random  # choose among {interleave, random}

# for rejection sampling
rejection_scheduler:
  method: uniform
  timesteps_to_select: 2

# for best-of-n sampling
best_of_n_scheduler:
  method: latest
  timesteps_to_select: 1

# for support interval estimation
bootstrap:
  confidence: 0.99
  method: normal

classifier:
  checkpoint_dir: ComposableDiff/models
  dataset: ${model.dataset}
  im_size: ${model.image_size}
  filter_dim: 64

model:
  image_size: 128
  num_channels: 192
  num_res_blocks: 2
  channel_mult: ""
  num_heads: 1
  num_head_channels: 64
  num_heads_upsample: -1
  attention_resolutions: "32,16,8"
  dropout: 0.1
  text_ctx: 128
  xf_width: 512
  xf_layers: 16
  xf_heads: 8
  xf_final_ln: true
  xf_padding: true
  diffusion_steps: 1000
  noise_schedule: "squaredcos_cap_v2"
  timestep_respacing: "100"
  use_scale_shift_norm: false
  resblock_updown: true
  use_fp16: false
  cache_text_emb: false
  inpaint: false
  super_res: false
  raw_unet: true
  use_kl: false
  rescale_timesteps: false
  rescale_learned_sigmas: false

hydra:
  run:
    dir: .
  output_subdir: null
